# 应用服务WEB端口
server:
  port: 8080
  servlet:
    context-path: /wwc

# 应用名称
spring:
  application:
    name: work-weixin-customer

# log 日志配置 日志级别从低到高分为TRACE < DEBUG < INFO < WARN < ERROR < FATAL，如果设置为WARN，则低于WARN的信息都不会输出
logging:
  level:
    root: info
  file:
    path: /Users/alan.lan/Alan/Log/wwc/logs



